dataset:
  # Single-slice SDI 
  10X_DLPFC:
    patient_idx: 0
    slice_idx: 0
    epochs: 1000
    lr: 0.0005
    alpha: 1.0 # balancing parameter for feature reconstruction
    beta: 0.1 # balancing parameter for self-supervised contrastive loss
  MTG:
    patient_idx: 0
    slice_idx: 0
    epochs: 1000
    lr: 0.001
    alpha: 10.0 # balancing parameter for feature reconstruction
    beta: 10.0 # balancing parameter for self-supervised contrastive loss
  Mouse_Embryo:
    patient_idx: 0
    slice_idx: 0
    epochs: 1000
    lr: 0.005
    alpha: 10.0 # balancing parameter for feature reconstruction
    beta: 1.0 # balancing parameter for self-supervised contrastive loss
  NSCLC:
    patient_idx: 0
    slice_idx: 0
    epochs: 1000
    lr: 0.0005
    alpha: 1.0 # balancing parameter for feature reconstruction
    beta: 0.1 # balancing parameter for self-supervised contrastive loss