dataset:
  # Single-slice SDI 
  10X_DLPFC:
    patient_idx: 0
    slice_idx: 0
    epochs: 200
    lr: 0.0001
    rec_w: 10.0 # balancing parameter for reconstruction loss
    gcn_w: 0.1 # balancing parameter for gcn loss
    self_w: 1.0 # balancing parameter for self loss
  MTG:
    patient_idx: 0
    slice_idx: 0
    epochs: 200
    lr: 0.0001
    rec_w: 10.0 # balancing parameter for reconstruction loss
    gcn_w: 0.1 # balancing parameter for gcn loss
    self_w: 0.1 # balancing parameter for self loss
  Mouse_Embryo:
    patient_idx: 0
    slice_idx: 0
    epochs: 1000
    lr: 1e-05
    rec_w: 10.0 # balancing parameter for reconstruction loss
    gcn_w: 0.1 # balancing parameter for gcn loss
    self_w: 0.1 # balancing parameter for self loss
  NSCLC:
    patient_idx: 0
    slice_idx: 0
    epochs: 1000
    lr: 0.0001
    rec_w: 10.0 # balancing parameter for reconstruction loss
    gcn_w: 0.1 # balancing parameter for gcn loss
    self_w: 1.0 # balancing parameter for self loss