dataset:
  # Single-slice SDI 
  10X_DLPFC:
    patient_idx: 0
    slice_idx: 0
    epochs: 1200
    lr: 0.005
    alpha: 0.5 # Balancing parameter for DGI (self-supervised) loss
  MTG:
    patient_idx: 0
    slice_idx: 0
    epochs: 1200
    lr: 0.001
    alpha: 0.5 # Balancing parameter for DGI (self-supervised) loss
  Mouse_Embryo:
    patient_idx: 0
    slice_idx: 0
    epochs: 1200
    lr: 0.005
    alpha: 0.1 # Balancing parameter for DGI (self-supervised) loss
  NSCLC:
    patient_idx: 0
    slice_idx: 0
    epochs: 1200
    lr: 0.005
    alpha: 5.0 # Balancing parameter for DGI (self-supervised) loss